version: '3.4'

services:
  alpine-base:
    image: hackinglab/alpine-base:latest
    hostname: 'alpine-base'
    env_file:
      - ./6db3a534-70eb-40e5-8d6f-9839b46b53fb.env
    volumes:
      - ./6db3a534-70eb-40e5-8d6f-9839b46b53fb.gn:/goldnugget/6db3a534-70eb-40e5-8d6f-9839b46b53fb.gn
